# Default values for hello-world-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
registryPullSecrets: quay-registry-secret

image:
  repository: quay.io/alfresco/anaxes-hello-world-service
  tag: 0.1-SNAPSHOT
  pullPolicy: Always
  internalPort: 8080
service:
  name: hello-world-app-backend
  # If running on AWS choose LoadBalancer as service Type, for minikube use NodePort
  type: NodePort
  externalPort: 80
ingress:
  path: /hello-service
persistence: 
  enabled: true
  baseSize: 10Gi
  efs:
    enabled: false
    dns: fs-example.efs.us-east-1.amazonaws.com
    path: "/"
  
database:
  persistence:
    size: 2Gi

postgresql:
  imageTag: "10.1"
  persistence:
    subPath: "hello/postgres-data"
    existingClaim: "hello-world-database-data"